version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: sgtpi-backend:latest
    container_name: sgtpi-backend
    env_file:
      - environment.env
    restart: always
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./FrontEnd/Angular
      dockerfile: Dockerfile
    image: sgtpi-frontend:latest
    container_name: sgtpi-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
