
package com.SGTPI.SystemProject.models;


public enum ReportType {
    PACIENTES_TOTAL,
    PACIENTE_MAS_TURNOS,
    PACIENTE_MAS_TURNOS_MES,
    CANT_TURNOS_MES,
    TURNOS_DIA_DADO,
    TURNOS_CANCELADOS_TOTAL,
    TURNOS_REALIZADOS_TOTAL,
    PROMEDIO_DURACION_TURNOS,
    TURNOS_MES_ACTUAL,
    TURNOS_RANGO_FECHAS,
    DIA_MAYOR_CANT_TURNOS
}
